export const ERROR_CODES = {
  // Initialization errors
  INIT_FAILED: 'INIT_FAILED',
  START_FAILED: 'START_FAILED',
  
  // Step resolution errors
  STEP_RESOLUTION_FAILED: 'STEP_RESOLUTION_FAILED',
  ELEMENT_NOT_FOUND: 'ELEMENT_NOT_FOUND',
  ELEMENT_NOT_VISIBLE: 'ELEMENT_NOT_VISIBLE',
  ELEMENT_NOT_INTERACTABLE: 'ELEMENT_NOT_INTERACTABLE',
  ELEMENT_NOT_IN_VIEWPORT: 'ELEMENT_NOT_IN_VIEWPORT',
  ELEMENT_UNSTABLE: 'ELEMENT_UNSTABLE',
  
  // Overlay rendering errors
  RENDER_FAILED: 'RENDER_FAILED',
  OVERLAY_FAILED: 'OVERLAY_FAILED',
  SPOTLIGHT_FAILED: 'SPOTLIGHT_FAILED',
  ZINDEX_CONFLICT: 'ZINDEX_CONFLICT',
  
  // State management errors
  STATE_UPDATE_FAILED: 'STATE_UPDATE_FAILED',
  STATE_CORRUPTION: 'STATE_CORRUPTION',
  PERSISTENCE_FAILED: 'PERSISTENCE_FAILED',
  STATE_DESYNC: 'STATE_DESYNC',
  
  // Error handling errors
  ERROR_HANDLING_FAILED: 'ERROR_HANDLING_FAILED',
  RECOVERY_FAILED: 'RECOVERY_FAILED',
  SAFE_FAILURE_FAILED: 'SAFE_FAILURE_FAILED',
  
  // Navigation errors
  NAVIGATION_FAILED: 'NAVIGATION_FAILED',
  LOCATION_MISMATCH: 'LOCATION_MISMATCH',
  ROUTE_CHANGE_TIMEOUT: 'ROUTE_CHANGE_TIMEOUT',
  
  // Validation errors
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  PRECONDITION_FAILED: 'PRECONDITION_FAILED',
  POSTCONDITION_FAILED: 'POSTCONDITION_FAILED',
  
  // Performance errors
  PERFORMANCE_DEGRADATION: 'PERFORMANCE_DEGRADATION',
  MEMORY_LEAK: 'MEMORY_LEAK',
  TIMEOUT_EXCEEDED: 'TIMEOUT_EXCEEDED',
  
  // Security errors
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  CROSS_ORIGIN_BLOCKED: 'CROSS_ORIGIN_BLOCKED',
  SECURITY_VIOLATION: 'SECURITY_VIOLATION',
  
  // Configuration errors
  INVALID_CONFIGURATION: 'INVALID_CONFIGURATION',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_SELECTOR: 'INVALID_SELECTOR',
  
  // System errors
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  CRITICAL_FAILURE: 'CRITICAL_FAILURE',
  SYSTEM_UNAVAILABLE: 'SYSTEM_UNAVAILABLE'
} as const;

export const ERROR_SEVERITY = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical'
} as const;

export const RECOVERY_STRATEGIES = {
  RETRY: 'retry',
  SKIP: 'skip',
  ABORT: 'abort',
  FALLBACK: 'fallback',
  EMERGENCY_SHUTDOWN: 'emergency-shutdown'
} as const;

export const ERROR_CATEGORIES = {
  INITIALIZATION: 'initialization',
  RESOLUTION: 'resolution',
  RENDERING: 'rendering',
  STATE: 'state',
  NAVIGATION: 'navigation',
  VALIDATION: 'validation',
  PERFORMANCE: 'performance',
  SECURITY: 'security',
  CONFIGURATION: 'configuration',
  SYSTEM: 'system'
} as const;
