export const MESSAGE_TYPES = {
  // Core system messages
  WALKTHROUGH_INIT: 'WALKTHROUGH_INIT',
  WALKTHROUGH_START: 'WALKTHROUGH_START',
  WALKTHROUGH_PAUSE: 'WALKTHROUGH_PAUSE',
  WALKTHROUGH_RESUME: 'WALKTHROUGH_RESUME',
  WALKTHROUGH_COMPLETE: 'WALKTHROUGH_COMPLETE',
  WALKTHROUGH_ABORT: 'WALKTHROUGH_ABORT',
  
  // Step management messages
  STEP_ACTIVATE: 'STEP_ACTIVATE',
  STEP_DEACTIVATE: 'STEP_DEACTIVATE',
  STEP_COMPLETE: 'STEP_COMPLETE',
  STEP_SKIP: 'STEP_SKIP',
  STEP_RETRY: 'STEP_RETRY',
  STEP_RESET: 'STEP_RESET',
  
  // Element resolution messages
  ELEMENT_RESOLVE: 'ELEMENT_RESOLVE',
  ELEMENT_RESOLVED: 'ELEMENT_RESOLVED',
  ELEMENT_NOT_FOUND: 'ELEMENT_NOT_FOUND',
  ELEMENT_UPDATED: 'ELEMENT_UPDATED',
  
  // Overlay messages
  OVERLAY_CREATE: 'OVERLAY_CREATE',
  OVERLAY_UPDATE: 'OVERLAY_UPDATE',
  OVERLAY_DESTROY: 'OVERLAY_DESTROY',
  OVERLAY_SHOW: 'OVERLAY_SHOW',
  OVERLAY_HIDE: 'OVERLAY_HIDE',
  
  // Spotlight messages
  SPOTLIGHT_CREATE: 'SPOTLIGHT_CREATE',
  SPOTLIGHT_UPDATE: 'SPOTLIGHT_UPDATE',
  SPOTLIGHT_DESTROY: 'SPOTLIGHT_DESTROY',
  SPOTLIGHT_ANIMATE: 'SPOTLIGHT_ANIMATE',
  
  // Event handling messages
  EVENT_INTERCEPT: 'EVENT_INTERCEPT',
  EVENT_ALLOW: 'EVENT_ALLOW',
  EVENT_BLOCK: 'EVENT_BLOCK',
  EVENT_RESTORE: 'EVENT_RESTORE',
  
  // State management messages
  STATE_UPDATE: 'STATE_UPDATE',
  STATE_SYNC: 'STATE_SYNC',
  STATE_PERSIST: 'STATE_PERSIST',
  STATE_RESTORE: 'STATE_RESTORE',
  STATE_RESET: 'STATE_RESET',
  
  // Progress messages
  PROGRESS_UPDATE: 'PROGRESS_UPDATE',
  PROGRESS_SAVE: 'PROGRESS_SAVE',
  PROGRESS_LOAD: 'PROGRESS_LOAD',
  
  // Error handling messages
  ERROR_OCCURRED: 'ERROR_OCCURRED',
  ERROR_LOG: 'ERROR_LOG',
  ERROR_RECOVER: 'ERROR_RECOVER',
  RECOVERY_ATTEMPT: 'RECOVERY_ATTEMPT',
  
  // Navigation messages
  ROUTE_CHANGE_DETECTED: 'ROUTE_CHANGE_DETECTED',
  NAVIGATION_BLOCKED: 'NAVIGATION_BLOCKED',
  NAVIGATION_ALLOWED: 'NAVIGATION_ALLOWED',
  
  // Validation messages
  STEP_LOCATION_VALIDATE: 'STEP_LOCATION_VALIDATE',
  VALIDATION_SUCCESS: 'VALIDATION_SUCCESS',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  
  // Debug messages
  DEBUG_INFO: 'DEBUG_INFO',
  DEBUG_EVENT: 'DEBUG_EVENT',
  DEBUG_METRICS: 'DEBUG_METRICS',
  
  // System messages
  SYSTEM_READY: 'SYSTEM_READY',
  SYSTEM_SHUTDOWN: 'SYSTEM_SHUTDOWN',
  PING: 'PING',
  PONG: 'PONG'
} as const;

export const MESSAGE_DIRECTIONS = {
  TO_BACKGROUND: 'to-background',
  TO_CONTENT: 'to-content',
  TO_OVERLAY: 'to-overlay',
  TO_STEP_ENGINE: 'to-step-engine',
  TO_STATE: 'to-state',
  BROADCAST: 'broadcast'
} as const;

export const MESSAGE_PRIORITIES = {
  LOW: 1,
  NORMAL: 2,
  HIGH: 3,
  CRITICAL: 4
} as const;

export const MESSAGE_TIMEOUTS = {
  DEFAULT: 5000,
  LONG: 15000,
  SHORT: 2000,
  CRITICAL: 1000
} as const;
